@startuml
'https://plantuml.com/sequence-diagram

box
!include file_posix_流程.puml!0
end box

box
!include PosixSequentialFile.puml!0
end box

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml