@startuml
'https://plantuml.com/sequence-diagram

autonumber

DB -> DB: 初始化 DBImpl
DB -> DB: mutex_.Lock()
DB -> DBImpl: impl->Recover()

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml